AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/*.rake'
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - bin/**/*
    - config/initializers/simple_form_bootstrap.rb*
    - config/initializers/devise.rb*
    - vendor/**/*
    - spec/support/**/*

Metrics/LineLength:
  Max: 120
MethodLength:
  Max: 30

Style/AccessorMethodName:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Style/IndentationWidth:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/Tab:
  Enabled: true

Style/TrailingBlankLines:
  Enabled: true

Style/TrailingWhitespace:
  Enabled: true
